# Generated by Django 5.0.4 on 2024-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0002_qrcode_delete_tfauser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
